<?php require_once './templates/header.phtml'?>



<h1>Nuestros productos son:</h1>

<form method="post" action="addProduct" class="form-control form-control-sm mb-3">
    <div class="row flex-row align-items-center">  
        <div class="col-auto">
            <label for="producto" class="h5">Ingrese su producto:</label>
            <input type="text" class="form-control" name="producto" id="producto"> 
        </div>
        <div class="col-auto">
            <label for="categoria" class="h5">Seleccione una Categoría:</label>
            <select class="form-select" name="categoria" id="categoria">
                <option value="">Seleccione una categoría</option> 
                <?php foreach($categorias as $item):?>
                    <option value="<?= $item->id_categoria?>"><?= $item->nombre_categoria?></option>
                <?php endforeach?>
            </select>
        </div>
        <div class="col-auto">
            <label for="precio" class="h5">Ingrese su precio:</label>
            <input type="number" class="form-control" name="precio" id="precio" maxlength="8">
        </div>
        
        <div class="col-auto">
            <button type="submit" class="btn btn-outline-success">Agregar</button>
        </div>
    </div>
</form>

<form method="post" action="filtrarProducto" class="form-control form-control-sm mb-3">
    <div class="row flex-row align-items-center"> 
        <div class="col-auto">
            <label for="filtroCategoria" class="h5">Filtrar por:</label>
        </div>
        <div class="col-auto">
            <select class="form-select" name="filtroCategoria" id="filtroCategoria">
                <option value="">Todas las categorías</option> 
                <?php foreach($categorias as $item):?>
                    <option value="<?= $item->id_categoria?>"><?= $item->nombre_categoria?></option>
                <?php endforeach?>
            </select>
        </div>
        <div class="col-auto">
            <button type="submit" class="btn btn-success">Filtrar</button>
        </div>
    </div>
</form>

<table class="table table-striped table-hover" style="background-color: #D09EE7;">
    <thead>
        <tr>
            <th>Nombre Producto</th>
            <th>categoria</th>
            <th>Precio</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($list as $item):?>
            <tr>
                <td><?= $item->nombre_producto ?></td>
                <td><?= $item->nombre_categoria ?></td>
                <td><?= $item->precio ?></td>
                <td><a href="editProducto/<?= $item->id ?>" class="btn btn-success">Editar</a></td> 
                <td><a href="removeProduct/<?= $item->id?>" class="btn btn-danger">Borrar</a></td>
            </tr>
        <?php endforeach?> 
    </tbody>
</table>

<?php require_once './templates/footer.phtml'?>